apiVersion: v1
kind: Service
metadata:
  name: equal-experts-solution
spec:
  selector:
    app: gist-api
  # "LoadBalancer" Cloud (AWS/GCP) par Real IP dega.
  # Local testing ke liye ye localhost par port forward karega.
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # Public world is port par aayegi
      targetPort: 8080 # Hamara container is port par sun raha hai